language: node_js
sudo: enabled
node_js:
  - "7"
install:
  - sudo apt-get update
  - curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo apt-get update
  - node --version
  - npm --version
  - sudo npm install -g coffeescript@next
  - sudo npm install -g firebase-tools
script:
  - ls -l
  - coffee -cb functions/
  - rm functions/*.coffee
  - coffee -cb public/
  - rm public/*.coffee
  - firebase --help
  - firebase deploy --token "$FIREBASE_TOKEN"
  - cd public/
  - ftp -inv $FTP_HOST.lima-ftp.de  <<END_SCRIPT \
    user $FTP_USER $FTP_PASSWD \
    mput * \
    bye \
    END_SCRIPT
