language: node_js
sudo: enabled
install:
  - npm install coffeescript
  - npm install -g firebase-tools
script:
  - coffee -cbo functions/ src/functions/
  - coffee -cbo public/ src/public/
  - firebase deploy --token "$FIREBASE_TOKEN"
  
