language: node_js
sudo: enabled
install:
  - curl -sL https://deb.nodesource.com/setup | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo npm install coffeescript
  - sudo npm install firebase-tools
script:
  - ls
  - coffee -cbo functions/ src/functions/
  - coffee -cbo public/ src/public/
  - npm install firebase-tools
  - firebase deploy --token "$FIREBASE_TOKEN"
  
