language: node_js
sudo: enabled
install:
  - curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo npm install -g coffeescript
  - sudo npm install -g firebase-tools
script:
  - ls
  - coffee -cbo functions/ src/functions/index.coffee
  - coffee -cbo public/ src/public/main.coffee
  - firebase deploy --token "$FIREBASE_TOKEN"
  
