language: node_js
sudo: enabled
node_js:
  - "7"
install:
  - node --version
  - npm --version
  - sudo npm install -g coffeescript
  - sudo npm install -g firebase-tools
script:
  - ls
  - coffee -cbo functions/ src/functions/
  - coffee -cbo public/ src/public/
  - firebase --help
  - firebase deploy --token "$FIREBASE_TOKEN"
  
