language: node_js
sudo: enabled
install:
  - sudo npm install coffeescript
script:
  - ls
  - coffee -cbo functions/ src/functions/
  - coffee -cbo public/ src/public/
  - npm install firebase-tools
  - firebase deploy --token "$FIREBASE_TOKEN"
  
