language: node_js
sudo: enabled
install:
  - sudo apt-get remove nodejs
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - node --version
  - npm --version
  - sudo npm install -g coffeescript
  - sudo npm install -g firebase-tools
script:
  - ls
  - coffee -cbo functions/ src/functions/
  - coffee -cbo public/ src/public/
  - firebase --help
  - firebase deploy --token "$FIREBASE_TOKEN"
  
